return {
    name = 'abed',
    offset = 5,
    ow = 7,
    costumes = {
        {name='Abed Nadir', sheet='base', category='base' },
        {name='Alien', sheet='alien', category='s2e6' },
        {name='Batman', sheet='batman', category='s1e7' },
        {name='Bumblebee', sheet='bee', category='s2e13' },
        -- {name='Cooperative Calligraphy', sheet='bottle', category='s2e8' },
        {name='Camouflage', sheet='camo', category='s1e23' },
        {name='Christmas Sweater', sheet='christmas', category='s3e10' },
        {name='Covered In Paint', sheet='paint', category='s2e24' },
        {name='Cowboy', sheet='cowboy', category='s2e21' },
        {name='Evil Abed', sheet='evil', category='s3e22' },
        -- {name='Frycook', sheet='frycook', category='s2e21' },
        {name='Gangster', sheet='gangster', category='s3e19' },
        {name='Han Solo', sheet='solo', category='s2e24' },
        {name='Inspector Spacetime', sheet='inspector', category='s3e5' },
        -- {name='Jack of Clubs', sheet='clubs', category='s2e23' },
        {name='Jeff Roleplay', sheet='jeff', category='s3e16' },
        {name='Joey', sheet='white', category='s1e17' },
        {name='Morning', sheet='morning', category='s2e7' },
        {name='Mouse King', sheet='king', category='s3e10' },
        {name='Pierce Roleplay', sheet='pierce', category='s3e16' },
        -- {name='Pillowtown', sheet='pillow', category='s3e14' },
        -- {name='Rod the Plumber', sheet='rod', category='s3e21' },
        -- {name='Toga', sheet='toga', category='s1e22' },
        {name='Troy and Abed Sewn Together', sheet='sewn', category='s3e5' },
        {name='Zombie', sheet='zombie', category='s2e6' }
    }
}
