local hilda = {}

hilda.sprite = love.graphics.newImage('images/hilda.png')
hilda.tickImage = love.graphics.newImage('images/heart.png')
hilda.menuImage = love.graphics.newImage('images/hilda_menu.png')
hilda.walk = true
hilda.items = {
    { ['text']='exit' },
    { ['text']='inventory' },
    { ['text']='command' },
    { ['text']='talk', ['option']={
        { ['text']='i am done with you' },
        { ['text']='i will wear your skin' },
        { ['text']='madam, i am on a quest', ['option']={
            { ['text']='more...', ['option']={
                { ['text']='i am done with you' },
                { ['text']='frog extinction' },
                { ['text']='ostrich' },
                { ['text']='other parrot' },
                { ['text']='anglerfish' },
                { ['text']='seal' },
                { ['text']='spider' },
                { ['text']='snake' },
                { ['text']='parrot' },
                { ['text']='swordfish' },
                { ['text']='rhino' },
                { ['text']='magic carpet' },
                { ['text']='rocket ship' },
                { ['text']='albatross' },
                { ['text']='ladder bug' },
                { ['text']='hidden pipe' },
                { ['text']='subcon vase' },
                { ['text']='magic flute' },
                { ['text']='star zone' },
                { ['text']='rashes' },
                { ['text']='zits' },
                { ['text']='pimples' },
                { ['text']='dark queen' },
                { ['text']='mechanical' },
                { ['text']='stoneship' },
                { ['text']='channel wood' },
                { ['text']='space ship' },
                { ['text']='old man trainer' },
                { ['text']='fly on a bird' },
                { ['text']='cinnamon island' },
                { ['text']='seal along the shore' },
                { ['text']='black lightning' },
                { ['text']='hornet' },
                { ['text']='shredder' },
                { ['text']='avenger' },
                { ['text']='wine hat' },
                { ['text']='magic feather' },
                { ['text']='raccoon clothes' },
                { ['text']='running jump' },
                { ['text']='collect all blue coins' },
                { ['text']='island of annoying voices' },
                { ['text']='hot tub end boss' },
                { ['text']='mustached mushroom' },
                { ['text']='bell toss' },
                { ['text']='charged fireball' },
                { ['text']='time bombs' },
                { ['text']='rock punch' },
                { ['text']='blue fire' },
                { ['text']='green fire' },
                { ['text']='purple fire' },
                { ['text']='boring regular old fire' },
                { ['text']='flying war ships' },
                { ['text']='clown face helicopter' },
                { ['text']='teeter totter flying floor' },
                { ['text']='unstable bath' },
                { ['text']='impervious to lava' },
                { ['text']='underwater exploration' },
                { ['text']='hover puppy' },
                { ['text']='giant ant dance club' },
                { ['text']='good karma quests' },
                { ['text']='fun quests' },
                { ['text']='unkillable bears' },
                { ['text']='antiphysics horse' },
                { ['text']='bubble attack' },
                { ['text']='leaf attack' },
                { ['text']='time freeze attack' },
                { ['text']='metal blade attack' },
                { ['text']='egg treatment' },
                { ['text']='blue poultry' },
                { ['text']='the chicken lady' },
                { ['text']='forest fungus' },
                { ['text']='wild children' },
                { ['text']='trippy potions' },
                { ['text']='pharmacist' },
                { ['text']='sawing small trees' },
                { ['text']='carpenter camps' },
                { ['text']='broken swords' },
                { ['text']='giant rock monster' },
                { ['text']='frog prescriptions' },
                { ['text']='vision medication' },
                { ['text']='brick vouchers' },
                { ['text']='extra large swords' },
            }},
            { ['text']='i am done with you' },
            { ['text']='throne of hawkthorne' },
            { ['text']='for your hand' },
        }},
        { ['text']='stand aside' },
    }},
}

hilda.responses = {
    ['madam, i am on a quest']={
        'I can help with that',
        'I have information on many topics...',
    },
    ['throne of hawkthorne']={
        'The throne is in Castle Hawkthorne,',
        'north of here. You unlock the castle with',
        'the white crystal of discipline,',
        'which you must free from the black caverns.',
    },
    ['frog extinction']={
        'You know what? My prank is going to cause a sea of',
        'laughter, and I am going to watch you drown in it!',
    },
    ['ostrich']={
        "I like ostriches, but also, I don't?",
        "I don't support ostriches. They're unfair to pigeons.",
        "I guess that's why you never see them",
        "on the same continent.",
    },
    ['other parrot']={
        'In the toughest jungle in the world,',
        "there are the big time parrots,",
        "and then there's the Other Parrots.",
    },
    ['anglerfish']={
        "A violent fish, prone to aggression.",
        "You wouldn't like him when he's anglery",
    },
    ['seal']={
        "You can unlock this by getting kissed,",
        "by a rose on the grey",
    },
    ['spider']={
        "We're gonna make Spiderman black now?",
        "Why don't we just have Michael Cera play Shaft?",
    },
    ['snake']={
        "Snake? Snake?!",
        "SNAAAAAAKKK EEEEEE!!!",
    },
    ['parrot']={
        "This parrot is no more!",
        "He has ceased to be!",
    },
    ['swordfish']={
        "An underrated movie starring Wolverine,",
        "it's still not as good as Blade.",
    },
    ['rhino']={
        "Oh, this was just a nickname that I got in college.",
        "Don't worry about it.",
    },
    ['magic carpet']={
        "Almost always piloted by friendly...",
        "yet sexually ambiguous Glee club instructors.",
    },
    ['rocket ship']={
        "Just as KFC's secret process seals in the flavor,",
        "I'm sealing in the cabin's air",
        "so you don't explode on your journey.",
    },
    ['albatross']={
        "Albatrosses are one of the biggest birds in the world.",
        "Many species of albatross are close to extinction,",
        "therefore we must try harder.",
    },
    ['ladder bug']={
        "Welcome to... ladders",
        "**applause**",
    },
    ['hidden pipe']={
        "It's hidden.",
    },
    ['subcon vase']={
        'Breaking this vase forces you into a dream-like state,',
        'filled with your subconscious.',
    },
    ['magic flute']={
        'Playing one of these may cause you to be transported',
        'to far off worlds that will frustrate you even more',
    },
    ['star zone']={
        'In my opinion, there is only one star worth studying.',
        'It is a black hole called Sagittarius A,',
        'located in the center of our galaxy.',
        'It has the density of 40 suns. Just like my wiener.',
    },
    ['rashes']={
        "I'm not getting flustered,",
        "these things on my chest are just rashes.",
        "I'm allergic to beans.",
    },
    ['zits']={
        'Like pimples, but too small to pop.',
        'Caused by poor breeding',
    },
    ['pimples']={
        'Whenever Magnitude gets a pimple,',
        'he knows what to do',
    },
    ['dark queen']=nil,
    ['mechanical']=nil,
    ['stoneship']={
        "Theoretically indestructible,",
        "but poke a hole in it and it'll sink like a rock.",
    },
    ['channel wood']=nil,
    ['space ship']={
        "In the future",
        "two cardboard boxes",
        "are about to become",
        "SPACE SHIPS",
    },
    ['old man trainer']=nil,
    ['fly on a bird']=nil,
    ['cinnamon island']=nil,
    ['seal along the shore']=nil,
    ['black lightning']={
        "Faster than white lightning.",
    },
    ['hornet']=nil,
    ['shredder']=nil,
    ['avenger']=nil,
    ['wine hat']=nil,
    ['magic feather']=nil,
    ['raccoon clothes']=nil,
    ['running jump']=nil,
    ['collect all blue coins']=nil,
    ['island of annoying voices']=nil,
    ['hot tub end boss']=nil,
    ['mustached mushroom']=nil,
    ['bell toss']=nil,
    ['charged fireball']=nil,
    ['time bombs']=nil,
    ['rock punch']=nil,
    ['blue fire']=nil,
    ['green fire']=nil,
    ['purple fire']=nil,
    ['boring regular old fire']=nil,
    ['flying war ships']=nil,
    ['clown face helicopter']=nil,
    ['teeter totter flying floor']=nil,
    ['unstable bath']=nil,
    ['impervious to lava']=nil,
    ['underwater exploration']=nil,
    ['hover puppy']=nil,
    ['giant ant dance club']=nil,
    ['good karma quests']=nil,
    ['fun quests']=nil,
    ['unkillable bears']=nil,
    ['antiphysics horse']=nil,
    ['bubble attack']=nil,
    ['leaf attack']=nil,
    ['time freeze attack']=nil,
    ['metal blade attack']=nil,
    ['egg treatment']=nil,
    ['blue poultry']=nil,
    ['the chicken lady']=nil,
    ['forest fungus']=nil,
    ['wild children']=nil,
    ['trippy potions']=nil,
    ['pharmacist']=nil,
    ['sawing small trees']=nil,
    ['carpenter camps']=nil,
    ['broken swords']=nil,
    ['giant rock monster']=nil,
    ['frog prescriptions']=nil,
    ['vision medication']=nil,
    ['brick vouchers']=nil,
    ['extra large swords']=nil,
}


return hilda
