require("busted")
require("src/utils")

describe("Various utility functions", function()

  describe("math.sign", function()
    it("should be -1 for a negative number", function()
      assert.are.equal(math.sign(-100), -1)
    end)
    it("should be 0 for a 0", function()
      assert.are.equal(math.sign(0), 0)
    end)
    it("should be 1 for a positive number", function()
      assert.are.equal(math.sign(100), 1)
    end)
  end)
  
  describe("math.round", function()
    it("should round 1.4 to 1", function()
      assert.are.equal(math.round(1.4), 1)
    end)
    it("should round 1.5 to 2", function()
      assert.are.equal(math.round(1.5), 2)
    end)
  end)

  describe("splitting strings", function()
    it("should split a string", function()
      assert.are.same(split("a a", " "), {"a", "a"})
    end)
  end)
  
end)
