#!/usr/bin/env python
import json

stats = json.load(open('stats.json'))
total = 0

for key, value in stats.items():
    print "{}\t{}".format(key, value)
    total += value

print "Total\t{}".format(total)
