local Gamestate = require 'vendor/gamestate'
local window = require 'window'
local camera = require 'camera'
local state = Gamestate.new()

function state:init()
end

function state:enter(previous)
    love.graphics.setBackgroundColor(0, 0, 0)
    self.music = love.audio.play("audio/credits.ogg", "stream", true)
    self.ty = 0
    camera:setPosition(0, self.ty)
    self.previous = previous
end

function state:leave()
    love.audio.stop(self.music)
end

function state:update(dt)
    self.ty = self.ty + 50 * dt
    camera:setPosition(0, self.ty)
end

function state:keypressed(key)
    if key == 'escape' or key == 'return' then
        Gamestate.switch(self.previous)
    end
end

function state:draw()
    love.graphics.printf('CREDITS', 0, 275, window.width, 'center')
    love.graphics.printf('6sutters', 0, 300, window.width, 'center')
    love.graphics.printf('a8252359', 0, 325, window.width, 'center')
    love.graphics.printf('aaronpetykowski', 0, 350, window.width, 'center')
    love.graphics.printf('acedia', 0, 375, window.width, 'center')
    love.graphics.printf('afiveseven', 0, 400, window.width, 'center')
    love.graphics.printf('afuturepresident', 0, 425, window.width, 'center')
    love.graphics.printf('ajay182', 0, 450, window.width, 'center')
    love.graphics.printf('akobrandon', 0, 475, window.width, 'center')
    love.graphics.printf('alpenghandi', 0, 500, window.width, 'center')
    love.graphics.printf('andyantsypants', 0, 525, window.width, 'center')
    love.graphics.printf('anton9109', 0, 550, window.width, 'center')
    love.graphics.printf('asdf', 0, 575, window.width, 'center')
    love.graphics.printf('atbvids', 0, 600, window.width, 'center')
    love.graphics.printf('automatic_taglines', 0, 625, window.width, 'center')
    love.graphics.printf('barry.se', 0, 650, window.width, 'center')
    love.graphics.printf('beebes', 0, 675, window.width, 'center')
    love.graphics.printf('beforemonsters', 0, 700, window.width, 'center')
    love.graphics.printf('benfranklinchang', 0, 725, window.width, 'center')
    love.graphics.printf('benlew', 0, 750, window.width, 'center')
    love.graphics.printf('boobatron', 0, 775, window.width, 'center')
    love.graphics.printf('boobatron4000', 0, 800, window.width, 'center')
    love.graphics.printf('calledieu', 0, 825, window.width, 'center')
    love.graphics.printf('charmee', 0, 850, window.width, 'center')
    love.graphics.printf('childish_gambino3', 0, 875, window.width, 'center')
    love.graphics.printf('clairelabear', 0, 900, window.width, 'center')
    love.graphics.printf('claywin', 0, 925, window.width, 'center')
    love.graphics.printf('clogan1', 0, 950, window.width, 'center')
    love.graphics.printf('cmdoptesc', 0, 975, window.width, 'center')
    love.graphics.printf('covertpz', 0, 1000, window.width, 'center')
    love.graphics.printf('cptbooyah', 0, 1025, window.width, 'center')
    love.graphics.printf('creekee', 0, 1050, window.width, 'center')
    love.graphics.printf('cyberpie118', 0, 1075, window.width, 'center')
    love.graphics.printf('de3ertf0x', 0, 1100, window.width, 'center')
    love.graphics.printf('deadpoolismyhomeboy', 0, 1125, window.width, 'center')
    love.graphics.printf('deckhipstername', 0, 1150, window.width, 'center')
    love.graphics.printf('delicioussoma', 0, 1175, window.width, 'center')
    love.graphics.printf('derferman', 0, 1200, window.width, 'center')
    love.graphics.printf('dontgochinatownme', 0, 1225, window.width, 'center')
    love.graphics.printf('dr. awesome', 0, 1250, window.width, 'center')
    love.graphics.printf('easilyremember', 0, 1275, window.width, 'center')
    love.graphics.printf('edisonout', 0, 1300, window.width, 'center')
    love.graphics.printf('elfaisa', 0, 1325, window.width, 'center')
    love.graphics.printf('eviltimmy', 0, 1350, window.width, 'center')
    love.graphics.printf('fanjeta123', 0, 1375, window.width, 'center')
    love.graphics.printf('fardy', 0, 1400, window.width, 'center')
    love.graphics.printf('fieldafar', 0, 1425, window.width, 'center')
    love.graphics.printf('gameoftardises', 0, 1450, window.width, 'center')
    love.graphics.printf('gizmo9002', 0, 1475, window.width, 'center')
    love.graphics.printf('glasenator', 0, 1500, window.width, 'center')
    love.graphics.printf('hbjudo17', 0, 1525, window.width, 'center')
    love.graphics.printf('heikon', 0, 1550, window.width, 'center')
    love.graphics.printf('hisfavouriteflavour', 0, 1575, window.width, 'center')
    love.graphics.printf('holyhandgnade13', 0, 1600, window.width, 'center')
    love.graphics.printf('idontusereddit', 0, 1625, window.width, 'center')
    love.graphics.printf('jackim', 0, 1650, window.width, 'center')
    love.graphics.printf('james92498', 0, 1675, window.width, 'center')
    love.graphics.printf('janaya', 0, 1700, window.width, 'center')
    love.graphics.printf('jewporn', 0, 1725, window.width, 'center')
    love.graphics.printf('jjangu', 0, 1750, window.width, 'center')
    love.graphics.printf('joshcorr', 0, 1775, window.width, 'center')
    love.graphics.printf('jpole1', 0, 1800, window.width, 'center')
    love.graphics.printf('jscuur', 0, 1825, window.width, 'center')
    love.graphics.printf('kastian', 0, 1850, window.width, 'center')
    love.graphics.printf('kaworus_lover', 0, 1875, window.width, 'center')
    love.graphics.printf('kazook', 0, 1900, window.width, 'center')
    love.graphics.printf('kcig', 0, 1925, window.width, 'center')
    love.graphics.printf('kilakev', 0, 1950, window.width, 'center')
    love.graphics.printf('klosec12', 0, 1975, window.width, 'center')
    love.graphics.printf('konyismydad', 0, 2000, window.width, 'center')
    love.graphics.printf('lasternom', 0, 2025, window.width, 'center')
    love.graphics.printf('lavenenosa', 0, 2050, window.width, 'center')
    love.graphics.printf('lifedreamcreate', 0, 2075, window.width, 'center')
    love.graphics.printf('lily_is_i', 0, 2100, window.width, 'center')
    love.graphics.printf('liwaldo', 0, 2125, window.width, 'center')
    love.graphics.printf('lvl5lazorlotus', 0, 2150, window.width, 'center')
    love.graphics.printf('m_a_d', 0, 2175, window.width, 'center')
    love.graphics.printf('majestic_moose', 0, 2200, window.width, 'center')
    love.graphics.printf('mario3d', 0, 2225, window.width, 'center')
    love.graphics.printf('mckriet', 0, 2250, window.width, 'center')
    love.graphics.printf('midnightbarber', 0, 2275, window.width, 'center')
    love.graphics.printf('mister_spider', 0, 2300, window.width, 'center')
    love.graphics.printf('nachojarred', 0, 2325, window.width, 'center')
    love.graphics.printf('nbieter', 0, 2350, window.width, 'center')
    love.graphics.printf('necral', 0, 2375, window.width, 'center')
    love.graphics.printf('necromanteion', 0, 2400, window.width, 'center')
    love.graphics.printf('nerdsavvy', 0, 2425, window.width, 'center')
    love.graphics.printf('nonisredael', 0, 2450, window.width, 'center')
    love.graphics.printf('notfreshprince', 0, 2475, window.width, 'center')
    love.graphics.printf('nyan_swanson', 0, 2500, window.width, 'center')
    love.graphics.printf('octocycle2', 0, 2525, window.width, 'center')
    love.graphics.printf('ohhoee', 0, 2550, window.width, 'center')
    love.graphics.printf('ohsin', 0, 2575, window.width, 'center')
    love.graphics.printf('outlandishflamingo', 0, 2600, window.width, 'center')
    love.graphics.printf('paintyfilms', 0, 2625, window.width, 'center')
    love.graphics.printf('paragon19', 0, 2650, window.width, 'center')
    love.graphics.printf('period blood', 0, 2675, window.width, 'center')
    love.graphics.printf('philoctitties', 0, 2700, window.width, 'center')
    love.graphics.printf('piratejesus', 0, 2725, window.width, 'center')
    love.graphics.printf('profbauer', 0, 2750, window.width, 'center')
    love.graphics.printf('rahmeeroh', 0, 2775, window.width, 'center')
    love.graphics.printf('rainfly_x', 0, 2800, window.width, 'center')
    love.graphics.printf('renako', 0, 2825, window.width, 'center')
    love.graphics.printf('roundy210', 0, 2850, window.width, 'center')
    love.graphics.printf('safetytorch', 0, 2875, window.width, 'center')
    love.graphics.printf('sallybranch', 0, 2900, window.width, 'center')
    love.graphics.printf('seanbroney', 0, 2925, window.width, 'center')
    love.graphics.printf('sherlockholme', 0, 2950, window.width, 'center')
    love.graphics.printf('shnook21', 0, 2975, window.width, 'center')
    love.graphics.printf('snokone', 0, 3000, window.width, 'center')
    love.graphics.printf('spritefan', 0, 3025, window.width, 'center')
    love.graphics.printf('sprneon', 0, 3050, window.width, 'center')
    love.graphics.printf('szprega', 0, 3075, window.width, 'center')
    love.graphics.printf('tgnsd', 0, 3100, window.width, 'center')
    love.graphics.printf('the govnor', 0, 3125, window.width, 'center')
    love.graphics.printf('thejordyd', 0, 3150, window.width, 'center')
    love.graphics.printf('thekurtin', 0, 3175, window.width, 'center')
    love.graphics.printf('thomasmb', 0, 3200, window.width, 'center')
    love.graphics.printf('trevorstarick', 0, 3225, window.width, 'center')
    love.graphics.printf('tristian', 0, 3250, window.width, 'center')
    love.graphics.printf('tristianshaut', 0, 3275, window.width, 'center')
    love.graphics.printf('unameriquinn', 0, 3300, window.width, 'center')
    love.graphics.printf('vintagefuture', 0, 3325, window.width, 'center')
    love.graphics.printf('vontd', 0, 3350, window.width, 'center')
    love.graphics.printf('wilburwright', 0, 3375, window.width, 'center')
    love.graphics.printf('wubbledaddy', 0, 3400, window.width, 'center')
    love.graphics.printf('wyken', 0, 3425, window.width, 'center')
    love.graphics.printf('xiaorobear', 0, 3450, window.width, 'center')
    love.graphics.printf('zaxerone', 0, 3475, window.width, 'center')
    love.graphics.printf('zhai', 0, 3500, window.width, 'center')
    
end

return state


